# Generated by Django 4.2.9 on 2024-05-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_apartment_image_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
